# Generated by Django 6.0.3 on 2026-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productsize_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_add',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
